version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - HOPSWORKS_API_KEY=djdhFrqCIxvo6ApQ.xERPM8BgPzFrbYJVj0uf2EavQ8PPSbp9nIytq13qINXxpjhNHPwU9XYRZEJ1hBUc
    volumes:
      - .:/app
    restart: unless-stopped